version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- pwsh: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ggg-killer/api/v2/package
  api_key:
    secure: efVomgLTCc8DpxiIdx+mjyZh1eDwjg6M5+SmMT9/boBtTRAtYkETugeeBShfQUr+
  skip_symbols: false
  symbol_server: https://www.myget.org/F/ggg-killer/api/v2/package
  on:
    branch: master
notifications:
- provider: Email
  to:
  - gggkiller2@gmail.com
  subject: AppVeyor - GParse - Build Failure
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
